In [1]:
from pynq import Overlay
import numpy as np

In [2]:
ol = Overlay("dSB_8J_512_axi_new.bit")

In [3]:
ol.ip_dict.keys()

dict_keys(['dSB_0', 'zynq_ultra_ps_e_0'])

In [4]:
dSB = ol.dSB_0

In [5]:
dSB.register_map

/usr/local/lib/python3.6/dist-packages/pynq/registers.py:393: UserWarning: Unsupported register size 1024 for register Memory_ps_x
  v[2], k
/usr/local/lib/python3.6/dist-packages/pynq/registers.py:393: UserWarning: Unsupported register size 1024 for register Memory_ps_y
  v[2], k


RegisterMap {
  CTRL = Register(AP_START=0, AP_DONE=0, AP_IDLE=1, AP_READY=0, RESERVED_1=0, AUTO_RESTART=0, RESERVED_2=0, INTERRUPT=0, RESERVED_3=0),
  GIER = Register(Enable=0, RESERVED=0),
  IP_IER = Register(CHAN0_INT_EN=0, CHAN1_INT_EN=0, RESERVED_0=0),
  IP_ISR = Register(CHAN0_INT_ST=0, CHAN1_INT_ST=0, RESERVED_0=0),
  ps_J_1 = Register(ps_J=0),
  ps_J_2 = Register(ps_J=0),
  ps_J_out_1 = Register(ps_J_out=0),
  ps_J_out_2 = Register(ps_J_out=0),
  c_0 = Register(c_0=0, RESERVED=0),
  dt = Register(dt=0, RESERVED=0)
}

In [6]:
N = 512

In [7]:
A = (-1)*np.ones((N, N)) + np.eye(N)

In [8]:
A

array([[ 0., -1., -1., ..., -1., -1., -1.],
       [-1.,  0., -1., ..., -1., -1., -1.],
       [-1., -1.,  0., ..., -1., -1., -1.],
       ...,
       [-1., -1., -1., ...,  0., -1., -1.],
       [-1., -1., -1., ..., -1.,  0., -1.],
       [-1., -1., -1., ..., -1., -1.,  0.]])

In [9]:
J = A

In [10]:
sum_J_power = 0
for i in range(N):
    for j in range(N):
        sum_J_power += J[i][j] * J[i][j]

In [11]:
xi = 0.5 * np.sqrt(N - 1) / np.sqrt(sum_J_power)

In [12]:
xi

0.022097086912079608

In [13]:
def ap_fixed_to_int(binary_str):
    """
    Convert a 16-bit two's complement fixed-point number to an integer.
    
    Args:
    binary_str (str): A 16-bit binary string
    
    Returns:
    float: The decimal integer value
    """
    # Validate input
    if len(binary_str) != 16:
        raise ValueError("Input must be a 16-bit binary string")
    
    # Check if it's a negative number (first bit is 1)
    if binary_str[0] == '1':
        # For negative numbers, invert the bits and add 1
        inverted = ''.join('1' if bit == '0' else '0' for bit in binary_str)
        return -(int(inverted, 2) + 1)
    else:
        # For positive numbers, simply convert to decimal
        return int(binary_str, 2)

def detailed_ap_fixed_conversion(binary_str):
    """
    Provide detailed conversion of a 16-bit two's complement fixed-point number.
    
    Args:
    binary_str (str): A 16-bit binary string
    
    Returns:
    dict: Detailed conversion information
    """
    # Validate input
    if len(binary_str) != 16:
        raise ValueError("Input must be a 16-bit binary string")
    
    # Breakdown the bits
    sign_bit = binary_str[0]
    integer_bits = binary_str[1:4]  # 3 magnitude bits for integer part
    fractional_bits = binary_str[4:]  # 12 fractional bits
    
    # Convert to integer value
    if sign_bit == '1':
        # Negative number: invert and add 1
        inverted = ''.join('1' if bit == '0' else '0' for bit in binary_str)
        int_value = -(int(inverted, 2) + 1)
    else:
        int_value = int(binary_str, 2)
    
    return {
        'binary': binary_str,
        'sign_bit': sign_bit,
        'integer_bits': integer_bits,
        'fractional_bits': fractional_bits,
        'integer_value': int_value,
        'decimal_representation': int_value / (2 ** 12)  # Divide by 2^12 due to 12 fractional bits
    }



In [14]:
def get_result_x(r_x):
    count = 0
    for j in range(N):
        count = j;
        c_a = count%2
        if c_a == 1:
            tmpt = dSB.read(0x400+4*int(count/2))
            cyc = bin(tmpt)[2:34]
            #print(cyc)
            cyc = cyc.zfill(32)
            #print(cyc)
            a = ap_fixed_to_int(cyc[0:16])
            #print(len(cyc[18:34]))
            #print(cyc)
            #print(cyc[18:34])
            b = ap_fixed_to_int(cyc[16:32])
            #print(a>>12, b>>12)
            #r_x[j-1] = np.sign(a)#>>12
            #r_x[j] = np.sign(b)#>>12
            r_x[j-1] = a/(2**14)
            r_x[j] = b/(2**14)
rx = np.zeros(N)

In [15]:
from pynq import allocate

In [16]:
# 分配内存 - 例如为4096×4096位分配空间
array_size = N * N  # 以uint32为单位的大小
data_buffer = allocate(shape=(array_size,), dtype=np.uint8)
data_buffer_out = allocate(shape=(array_size,), dtype=np.uint8)

In [17]:
# 设置特定位的值的函数
def set_bit(data, row, col, value):
    bit_position = row * N + col
    byte_index = bit_position // 8
    bit_offset = bit_position % 8
    
    if value:
        data[bit_position] = np.uint8(1)<<6
        #data[byte_index] |= (1 << bit_offset)  # 设置位为1
    else:
        data[bit_position] = np.uint8(0)<<6
        #data[byte_index] &= ~(1 << bit_offset)  # 设置位为0

# 填充数据（示例）
# 例如，创建一个棋盘图案
for i in range(N):
    for j in range(N):
        # 创建棋盘格图案作为示例
        value = 1 if i!=j else 0
        set_bit(data_buffer, i, j, value)

In [18]:
# 获取分配内存的设备地址
device_address = data_buffer.device_address

# 将64位地址拆分为两个32位部分
address_lower = device_address & 0xFFFFFFFF         # 低32位
address_upper = (device_address >> 32) & 0xFFFFFFFF # 高32位

# 写入地址到寄存器
dSB.write(0x010, address_lower)  # 低32位地址写入0x010寄存器
dSB.write(0x014, address_upper)  # 高32位地址写入0x014寄存器

In [19]:
# 获取分配内存的设备地址
device_address_out = data_buffer_out.device_address

# 将64位地址拆分为两个32位部分
address_lower_out = device_address_out & 0xFFFFFFFF         # 低32位
address_upper_out = (device_address_out >> 32) & 0xFFFFFFFF # 高32位

# 写入地址到寄存器
dSB.write(0x01c, address_lower_out)  # 低32位地址写入0x010寄存器
dSB.write(0x020, address_upper_out)  # 高32位地址写入0x014寄存器

In [20]:
x = 0.02 * (np.random.rand(N) - 0.5)
y = 0.02 * (np.random.rand(N) - 0.5)
for i in range(N):
    x[i] *= (2**14)
    y[i] *= (2**14)
x=x.astype(np.int16)
y=y.astype(np.int16)

In [21]:
%%time
dt = 0.003*(2**14)
print(dt)
xi = 0.022097086912079608*(2**14)
print(xi)
tmpt = np.zeros((2),dtype="int16")
tmpt[0] = np.int16(xi)
dSB.write(0x028, bytes(tmpt))
tmpt[0] = np.int16(dt)
dSB.write(0x030, bytes(tmpt))



count = 0
for j in range(N):
    count = j;
    c_a = count%2
    if c_a == 0:
        tmpt = np.zeros((2),dtype="int16")
    tmpt[c_a] = x[j]
    if c_a == 1:
        val = bytes(tmpt)
        dSB.write(0x400+4*int(count/2), val)

count = 0
for j in range(N):
    count = j;
    c_a = count%2
    if c_a == 0:
        tmpt = np.zeros((2),dtype="int16")
    tmpt[c_a] = y[j]
    if c_a == 1:
        val = bytes(tmpt)
        dSB.write(0x800+4*int(count/2), val)



49.152
362.0386719675123
CPU times: user 44.3 ms, sys: 2 µs, total: 44.3 ms
Wall time: 44.3 ms


In [22]:
%%time
dSB.write(0,1)

finished = dSB.read(0)
while(finished!=14):
    finished = dSB.read(0)

CPU times: user 134 ms, sys: 3.96 ms, total: 138 ms
Wall time: 137 ms


In [23]:
get_result_x(rx)
np.sum(rx<0)

256

In [24]:
rx

array([ 0.05688477, -0.13214111,  0.06365967,  0.05645752,  0.08770752,
        0.09881592, -0.10131836, -0.11535645, -0.12298584, -0.14813232,
        0.05895996, -0.14251709,  0.05664062, -0.12243652,  0.05279541,
        0.05987549,  0.05609131,  0.06048584, -0.10980225,  0.05706787,
       -0.1270752 ,  0.09564209, -0.10101318, -0.109375  , -0.11828613,
        0.08355713, -0.10150146, -0.12237549,  0.04449463,  0.04986572,
        0.05877686,  0.05993652,  0.06048584,  0.06549072, -0.07525635,
        0.05200195,  0.05712891, -0.10174561,  0.05334473,  0.08288574,
        0.05169678, -0.14227295, -0.09771729,  0.06561279, -0.11895752,
       -0.14422607,  0.08178711, -0.1217041 ,  0.0524292 , -0.10217285,
       -0.10131836, -0.11724854, -0.1182251 , -0.12957764, -0.11151123,
        0.06182861,  0.05993652, -0.12719727, -0.12097168,  0.05889893,
        0.05316162, -0.13793945, -0.11480713, -0.10351562, -0.12695312,
        0.06542969, -0.13830566, -0.11413574,  0.05908203,  0.05

In [25]:
import numpy as np

def get_bit_matrix(data, N):
    """
    从数据缓冲区读取位信息，并构建N×N的矩阵
    
    参数:
        data: 包含位数据的缓冲区
        N: 矩阵的维度
    
    返回:
        N×N的numpy矩阵，包含位值（0或1）
    """
    # 创建一个N×N的零矩阵
    matrix = np.zeros((N, N), dtype=np.uint8)
    
    # 遍历矩阵的每个位置
    for i in range(N):
        for j in range(N):
            bit_position = i * N + j
            # 根据你的设置函数逻辑，检查位值
            if data[bit_position] == np.uint8(1)<<6:
                matrix[i, j] = 1
            else:
                matrix[i, j] = 0
    
    return matrix

# 使用示例
# 假设 data_buffer 和 N 已经定义
# matrix = get_bit_matrix(data_buffer, N)
# print(matrix)

In [26]:
get_bit_matrix(data_buffer, N)

array([[0, 1, 1, ..., 1, 1, 1],
       [1, 0, 1, ..., 1, 1, 1],
       [1, 1, 0, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 0, 1, 1],
       [1, 1, 1, ..., 1, 0, 1],
       [1, 1, 1, ..., 1, 1, 0]], dtype=uint8)